version: '3.8' # 建議使用較新的版本
services:
  mysql_db:
    image: mysql:9.4.0
    container_name: mysql-compose
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
